pull_request_rules:
  - name: Merge when CI passes and resolves all requested reviews
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - status-success=continuous-integration/travis-ci/pr
      - status-success=clahub
      - base=master
      - label!=do-not-merge
      - "- title~=\\b(wip|WIP)\\b"
    actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: smart
