[package]
description = "Recursive-length prefix encoding, decoding, and compression"
repository = "https://github.com/paritytech/parity"
license = "MIT/Apache-2.0"
name = "rlp"
version = "0.2.1"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
elastic-array = "0.10"
primitives = { git = "https://github.com/CodeChain-io/rust-codechain-primitives.git", version = "0.4" }
rustc-hex = "1.0"
