[package]
name = "triehash"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "in memory patricia trie operations"
license = "GPL-3.0"

[dependencies]
rlp = { version = "0.2.1", path = "../rlp" }
codechain-crypto = { path="../../crypto" }
primitives = { path="../primitives" }
