[package]
name = "kvdb-memorydb"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
parking_lot = "0.6.0"
kvdb = { path = "../kvdb" }
rlp = { git = "https://github.com/CodeChain-io/rlp.git", version = "0.3" }
