[package]
description = "CodeChain Reactor"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "codechain-reactor"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1.17"
